name: "build"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v3
        
      - name: "Build:dockerimage"
        uses: docker/build-push-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}
          repository: nv08/test-frontend
          tags: latest
          push: ${{ github.ref == 'refs/heads/main' }}
