name: "build"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
        - name: Add SHORT_SHA env property with commit short sha
          run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
          
        - name: print short SHA
          run: echo ${{ SHORT_SHA }}
          
        - name: Checkout
          uses: actions/checkout@v2

        - name: log into ghcr
          uses: docker/login-action@v2
          with: 
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.PAT }}

        
        - name: Build and push
          run: |
            docker build . --tag ghcr.io/nv08/frontend
            docker push ghcr.io/nv08/frontend


        # - name: Build and push
        #   uses: docker/build-push-action@v2
        #   with:
        #     registry: ghcr.io
        #     username: ${{ github.actor }}
        #     password: ${{ secrets.PAT }}
        #     repository: ghcr.io/frontend
        #     tags: latest

        # - name: push build
        #   run: docker push ghcr.io/frontend

        # - name: Set up QEMU
        #   uses: docker/setup-qemu-action@v2
        
        # - name: set up docker buildx
        #   uses: docker/setup-buildx-action@v2

        # - name: Login to dockerhub
        #   uses: docker/login-action@v2
        #   with:
        #     username: ${{ secrets.DOCKERHUB_USERNAME }}
        #     password: ${{ secrets.DOCKERHUB_TOKEN }}

        # - name: Build and push
        #   uses: docker/build-push-action@v2
        #   with:
        #     registry: ghcr.io
        #     username: ${{ github.actor }}
        #     password: ${{ secrets.PAT }}
        #     repository: nv08/test-frontend
        #     tags: latest

      # - name: "Build:checkout"
      #   uses: actions/checkout@v3
        
      # - name: "Build:dockerimage"
      #   uses: docker/build-push-action@v2
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.PAT }}
      #     repository: nv08/test-frontend
      #     tags: latest
      #     push: ${{ github.ref == 'refs/heads/main' }}
